### ISSUE TITLE
ImportError: cannot import name handlers

### ISSUE THREAD

**Issue by kkuehl** [MozillaSecurity/domfuzz#14]
python /domfuzz/dom/automation/loopdomfuzz.py --submit /build

root@7193fd2bfd66:/# python /domfuzz/dom/automation/loopdomfuzz.py --submit /build
Loading bool prefs

%%% 2018-01-05 20:59:31.621315 starting q1: file:/build/tests/reftest/tests/layout/reftests/font-inflation/threshold-input-text-contents-under-2.html#fuzz=3780413770,0,55,7,30000,0
detect_assertions is ready (ignoring 235 strings without filenames and 696 strings with filenames)
Traceback (most recent call last):
  File "/domfuzz/dom/automation/runbrowser.py", line 133, in <module>
    runBrowser()
  File "/domfuzz/dom/automation/runbrowser.py", line 54, in runBrowser
    from automation import Automation
  File "/build/tests/reftest/automation.py", line 25, in <module>
    import mozcrash
  File "/build/tests/mozbase/mozcrash/mozcrash/__init__.py", line 11, in <module>
    from .mozcrash import *
  File "/build/tests/mozbase/mozcrash/mozcrash/mozcrash.py", line 21, in <module>
    import mozlog
  File "/build/tests/mozbase/mozlog/mozlog/__init__.py", line 20, in <module>
    from . import commandline
  File "/build/tests/mozbase/mozlog/mozlog/commandline.py", line 13, in <module>
    from . import handlers
ImportError: cannot import name handlers
DOMFUZZ INFO | domInteresting.py | Terminated by signal 9000 (unknown signal)
Traceback (most recent call last):
  File "/domfuzz/dom/automation/loopdomfuzz.py", line 292, in <module>
    start_runs()
  File "/domfuzz/dom/automation/loopdomfuzz.py", line 281, in start_runs
    many_timed_runs(None, sps.createWtmpDir(os.getcwdu()), sys.argv[1:], collector, quiet=False)
  File "/domfuzz/dom/automation/loopdomfuzz.py", line 91, in many_timed_runs
    result = domInteresting.BrowserResult(bc, url, logPrefix, extraPrefs=extraPrefs, quiet=quiet)
  File "/domfuzz/dom/automation/domInteresting.py", line 656, in __init__
    assert alh.theapp
AssertionError

**Comment by kkuehl** [comment]
In /build/tests/mozbase/mozlog/mozlog/commandline.py
from handlers import *
may not be the correct fix, but it works.

**Comment by kkuehl** [comment]
build obtained via:
 python -m fuzzfetch -d -a -n /build --tests common reftests gtest

**Comment by kkuehl** [comment]
If I comment out
``` 
    # from mozterm import Terminal
```
in /build/tests/mozbase/mozlog/mozlog/formatters/machformatter.py

everything works. Not sure what has changed.

**Comment by kkuehl** [comment]
Fixed by running
python /build/tests/mozbase/setup_development.py 
Feel free to close
